services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # 仅保留DataFixtures相关配置用于测试环境
  Tourze\SupplierManageBundle\DataFixtures\:
    resource: '../../DataFixtures'
    tags: ['doctrine.fixture.orm']